### ISSUE TITLE
适配Pandora

### ISSUE THREAD

**Issue by Steph00L** [Gutsgwh1997/lidar_IMU_calib#1]
同学您好，我最近也想适配到自己的设备（禾赛的雷达）上，有些具体问题想交流，请问是否能加个微信

**Comment by Gutsgwh1997** [comment]
您好，若您的rosbag包中雷达消息是sensor_msgs/PointCloud2标准类型，当点云时间戳是点云起始点时刻，可修改calib.sh文件中lidar_model:="VLP_16" ；当点云时间戳是点云终止时刻，可修改lidar_model:="RS_LIDAR"，随后可直接使用。我的微信是gwh1085765792，欢迎交流。
