### ISSUE TITLE
在无人车这样的地面车辆上运动的数据集可以用么

### ISSUE THREAD

**Issue by daijiaoshou** [Gutsgwh1997/lidar_IMU_calib#2]

**Comment by Gutsgwh1997** [comment]
类似于无车人这种平面运动，这种方法是用不了的。难以保证IMU至少在两个轴向上充分被激励，此外退化运动（例如纯平移）还会增加lidar-imu标定的不可观测维度，这一部分的分析可以看LIC-Fusion 2.0-C章节，也是浙大大佬们的工作。

**Comment by daijiaoshou** [comment]
好的，谢谢
